/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesTickerRouteImport } from './routes/companies/$ticker'
import { Route as CompaniesTickerTranscriptYearQuarterRouteImport } from './routes/companies/$ticker/transcript.$year.$quarter'
import { Route as CompaniesTickerQuartersYearQuarterRouteImport } from './routes/companies/$ticker/quarters.$year.$quarter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesTickerRoute = CompaniesTickerRouteImport.update({
  id: '/companies/$ticker',
  path: '/companies/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesTickerTranscriptYearQuarterRoute =
  CompaniesTickerTranscriptYearQuarterRouteImport.update({
    id: '/transcript/$year/$quarter',
    path: '/transcript/$year/$quarter',
    getParentRoute: () => CompaniesTickerRoute,
  } as any)
const CompaniesTickerQuartersYearQuarterRoute =
  CompaniesTickerQuartersYearQuarterRouteImport.update({
    id: '/quarters/$year/$quarter',
    path: '/quarters/$year/$quarter',
    getParentRoute: () => CompaniesTickerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$ticker': typeof CompaniesTickerRouteWithChildren
  '/companies/$ticker/quarters/$year/$quarter': typeof CompaniesTickerQuartersYearQuarterRoute
  '/companies/$ticker/transcript/$year/$quarter': typeof CompaniesTickerTranscriptYearQuarterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$ticker': typeof CompaniesTickerRouteWithChildren
  '/companies/$ticker/quarters/$year/$quarter': typeof CompaniesTickerQuartersYearQuarterRoute
  '/companies/$ticker/transcript/$year/$quarter': typeof CompaniesTickerTranscriptYearQuarterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/$ticker': typeof CompaniesTickerRouteWithChildren
  '/companies/$ticker/quarters/$year/$quarter': typeof CompaniesTickerQuartersYearQuarterRoute
  '/companies/$ticker/transcript/$year/$quarter': typeof CompaniesTickerTranscriptYearQuarterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/$ticker'
    | '/companies/$ticker/quarters/$year/$quarter'
    | '/companies/$ticker/transcript/$year/$quarter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/$ticker'
    | '/companies/$ticker/quarters/$year/$quarter'
    | '/companies/$ticker/transcript/$year/$quarter'
  id:
    | '__root__'
    | '/'
    | '/companies/$ticker'
    | '/companies/$ticker/quarters/$year/$quarter'
    | '/companies/$ticker/transcript/$year/$quarter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesTickerRoute: typeof CompaniesTickerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$ticker': {
      id: '/companies/$ticker'
      path: '/companies/$ticker'
      fullPath: '/companies/$ticker'
      preLoaderRoute: typeof CompaniesTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$ticker/transcript/$year/$quarter': {
      id: '/companies/$ticker/transcript/$year/$quarter'
      path: '/transcript/$year/$quarter'
      fullPath: '/companies/$ticker/transcript/$year/$quarter'
      preLoaderRoute: typeof CompaniesTickerTranscriptYearQuarterRouteImport
      parentRoute: typeof CompaniesTickerRoute
    }
    '/companies/$ticker/quarters/$year/$quarter': {
      id: '/companies/$ticker/quarters/$year/$quarter'
      path: '/quarters/$year/$quarter'
      fullPath: '/companies/$ticker/quarters/$year/$quarter'
      preLoaderRoute: typeof CompaniesTickerQuartersYearQuarterRouteImport
      parentRoute: typeof CompaniesTickerRoute
    }
  }
}

interface CompaniesTickerRouteChildren {
  CompaniesTickerQuartersYearQuarterRoute: typeof CompaniesTickerQuartersYearQuarterRoute
  CompaniesTickerTranscriptYearQuarterRoute: typeof CompaniesTickerTranscriptYearQuarterRoute
}

const CompaniesTickerRouteChildren: CompaniesTickerRouteChildren = {
  CompaniesTickerQuartersYearQuarterRoute:
    CompaniesTickerQuartersYearQuarterRoute,
  CompaniesTickerTranscriptYearQuarterRoute:
    CompaniesTickerTranscriptYearQuarterRoute,
}

const CompaniesTickerRouteWithChildren = CompaniesTickerRoute._addFileChildren(
  CompaniesTickerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesTickerRoute: CompaniesTickerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
